### ISSUE TITLE
Axum example from docs does not compile

### ISSUE THREAD

**Issue by theguy147** [beltram/asserhttp#219]
Hey,

the Axum sample test from the docs does not currently compile and yields the following error message:

"error[E5099]: no method named `expect_status_ok` found for enum `Result` in the current scope"

I have only tried with `axum = "0.7.5"` and `asserhttp = { version = "0.6.1", features = ["axum"] }` for now.

I'll add more details after I managed to investigate further...

UPDATE:
Ok, in order for `asserhttp` to work with a current axum project the axum version in the Cargo.toml needs to be bumped and some minor adjustments are necessary in the `impl BodyAccessor for AxumResponse`.

**Comment by beltram** [comment]
Hey, thanks for noticing. I've fixed it differently though, feel free to check it out
